using System.Text.Json.Serialization;
using zborek.Langfuse.Models.Core;

namespace zborek.Langfuse.Models.Score;

/// <summary>
///     Request to update a score configuration (partial update)
/// </summary>
public class UpdateScoreConfigRequest
{
    /// <summary>
    ///     The status of the score config showing if it is archived or not
    /// </summary>
    [JsonPropertyName("isArchived")]
    public bool? IsArchived { get; set; }

    /// <summary>
    ///     The name of the score config
    /// </summary>
    [JsonPropertyName("name")]
    public string? Name { get; set; }

    /// <summary>
    ///     Configure custom categories for categorical scores.
    ///     Pass a list of objects with label and value properties.
    ///     Categories are autogenerated for boolean configs and cannot be passed.
    /// </summary>
    [JsonPropertyName("categories")]
    public ConfigCategory[]? Categories { get; set; }

    /// <summary>
    ///     Configure a minimum value for numerical scores.
    ///     If not set, the minimum value defaults to -∞
    /// </summary>
    [JsonPropertyName("minValue")]
    public double? MinValue { get; set; }

    /// <summary>
    ///     Configure a maximum value for numerical scores.
    ///     If not set, the maximum value defaults to +∞
    /// </summary>
    [JsonPropertyName("maxValue")]
    public double? MaxValue { get; set; }

    /// <summary>
    ///     Description is shown across the Langfuse UI and can be used to e.g.
    ///     explain the config categories in detail, why a numeric range was set,
    ///     or provide additional context on config name or usage
    /// </summary>
    [JsonPropertyName("description")]
    public string? Description { get; set; }
}
