using System.Text.Json.Serialization;
using zborek.Langfuse.Models.Model;

namespace zborek.Langfuse.Models.Observation;

/// <summary>
///     Usage statistics for LLM operations, including token counts and associated costs in USD.
/// </summary>
public class Usage
{
    /// <summary>
    ///     Number of input tokens consumed by the LLM for processing the request.
    /// </summary>
    [JsonPropertyName("input")]
    public int? Input { get; set; }

    /// <summary>
    ///     Number of output tokens generated by the LLM in the response.
    /// </summary>
    [JsonPropertyName("output")]
    public int? Output { get; set; }

    /// <summary>
    ///     Total number of tokens used (sum of input and output tokens).
    /// </summary>
    [JsonPropertyName("total")]
    public int? Total { get; set; }

    /// <summary>
    ///     Unit of measurement for usage values.
    /// </summary>
    [JsonPropertyName("unit")]
    public ModelUsageUnit? Unit { get; set; }

    /// <summary>
    ///     Cost in USD for processing input tokens, calculated based on the model's pricing.
    /// </summary>
    [JsonPropertyName("inputCost")]
    public double? InputCost { get; set; }

    /// <summary>
    ///     Cost in USD for generating output tokens, calculated based on the model's pricing.
    /// </summary>
    [JsonPropertyName("outputCost")]
    public double? OutputCost { get; set; }

    /// <summary>
    ///     Total cost in USD for the entire operation (sum of input and output costs).
    /// </summary>
    [JsonPropertyName("totalCost")]
    public double? TotalCost { get; set; }
}