namespace zborek.Langfuse.Models.Observation;

/// <summary>
///     Usage statistics for LLM operations, including token counts and associated costs in USD.
/// </summary>
public class Usage
{
    /// <summary>
    ///     Number of input tokens consumed by the LLM for processing the request.
    /// </summary>
    public int? InputTokens { get; set; }

    /// <summary>
    ///     Number of output tokens generated by the LLM in the response.
    /// </summary>
    public int? OutputTokens { get; set; }

    /// <summary>
    ///     Total number of tokens used (sum of input and output tokens).
    /// </summary>
    public int? TotalTokens { get; set; }

    /// <summary>
    ///     Cost in USD for processing input tokens, calculated based on the model's pricing.
    /// </summary>
    public decimal? InputCost { get; set; }

    /// <summary>
    ///     Cost in USD for generating output tokens, calculated based on the model's pricing.
    /// </summary>
    public decimal? OutputCost { get; set; }

    /// <summary>
    ///     Total cost in USD for the entire operation (sum of input and output costs).
    /// </summary>
    public decimal? TotalCost { get; set; }
}