//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Langfuse.Analyzers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Langfuse.Analyzers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When creating objects within a using statement, use the scoped variant to properly establish parent-child relationships.
        /// </summary>
        internal static string LANG001_Description {
            get {
                return ResourceManager.GetString("LANG001_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use &apos;{0}&apos; instead of &apos;{1}&apos; when creating objects in a using statement.
        /// </summary>
        internal static string LANG001_Format {
            get {
                return ResourceManager.GetString("LANG001_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-scoped method should not be used in using statement.
        /// </summary>
        internal static string LANG001_Title {
            get {
                return ResourceManager.GetString("LANG001_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scoped methods return disposables that must be properly disposed to maintain the parent context stack.
        /// </summary>
        internal static string LANG002_Description {
            get {
                return ResourceManager.GetString("LANG002_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be used within a using statement or assigned to a using variable.
        /// </summary>
        internal static string LANG002_Format {
            get {
                return ResourceManager.GetString("LANG002_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scoped method must be used with using statement.
        /// </summary>
        internal static string LANG002_Title {
            get {
                return ResourceManager.GetString("LANG002_Title", resourceCulture);
            }
        }
    }
}
