###
POST http://localhost:5146/chat
Content-Type: application/json

{
    "model": "gpt-4o-mini",
    "name": "Hello",
    "message": "Hello, World!"
}


###
POST http://localhost:5146/chatDi
Content-Type: application/json

{
    "model": "gpt-4o-mini",  
    "name": "Story",
    "message": "Write me very short story about dragons"
}